# Generated by Django 3.2.4 on 2021-06-20 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pelaporan', '0002_pelaporan_pelaporan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelaporan',
            old_name='Pelaporan',
            new_name='Pelapor',
        ),
    ]
