# Generated by Django 3.2.4 on 2021-06-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keterangan', '0003_peta_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peta',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
